import { Money } from "../value-objects/Money.js";

export default class InvoiceItem {
    constructor({ id, invoiceId, description, quantity, unitPrice, totalPrice, createdAt, updatedAt }) {
        this.id = id;
        this.invoiceId = invoiceId;
        this.description = description;
        this.quantity = quantity;
        this.unitPrice = new Money(unitPrice);
        this.totalPrice = new Money(totalPrice); // Should ideally be unitPrice * quantity
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    static create({ description, quantity, unitPrice }) {
        const uPrice = new Money(unitPrice);
        const tPrice = uPrice.multiply(quantity);

        return new InvoiceItem({
            id: null, // Generated by DB
            invoiceId: null, // Set when saving
            description,
            quantity,
            unitPrice: uPrice.amount,
            totalPrice: tPrice.amount
        });
    }

    toJSON() {
        return {
            id: this.id,
            invoiceId: this.invoiceId,
            description: this.description,
            quantity: this.quantity,
            unitPrice: this.unitPrice.toJSON(),
            totalPrice: this.totalPrice.toJSON(),
            createdAt: this.createdAt,
            updatedAt: this.updatedAt
        };
    }
}
